include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - **/*.g.dart

linter:
  rules:
    - avoid_print
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - file_names
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - non_constant_identifier_names
    - prefer_single_quotes
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - use_key_in_widget_constructors